### ISSUE TITLE
can't compile with ghc-7.10

### ISSUE THREAD

**Issue by chemist** [jeremyjh/higher-leveldb#2]
Compile success if higher-leveldb.cabal like:
  build-depends:       base == 4.*
                       , cereal
                       , lifted-base
                       , leveldb-haskell
                       , bytestring
                       , resourcet
                       , transformers-base
                       , mtl
                       , monad-control
                       , data-default
                       , transformers

**Comment by jeremyjh** [comment]
The issue was GHC 7.10 required mtl >= 2.2, and I had an upper bound on 2.2. I've uploaded a new version that supports mtl <= 2.3.
