### ISSUE TITLE
"scan" interface: exact role of the Key argument

### ISSUE THREAD

**Issue by runeksvendsen** [jeremyjh/higher-leveldb#3]
Hello

Thank you for making this wonderful library. Looks like everything I thought I needed to write myself has been wrapped in this `scan` interface.

I'm in doubt about the role of the Key, argument, to the `scan`function though. In the Haddock documentation, it says the key is `Key at which to start the scan` but in the example in this repo's README, a non-existing key is supplied as an argument.

What I'm looking for is a way to scan the entire key space, starting at the first item in the DB. In this case is it OK to just supply an empty string, ie. a non-existing key, as the `Key` argument to `scan`?

**Comment by jeremyjh** [comment]
The key can be a partial match or not even a match - it will just determine
where to start the scan. So yes, using empty string should start at the
beginning of the key space.

**Comment by runeksvendsen** [comment]
Alright, thank you Sir!
